#!/bin/bash
###########################################################################
# Repositorio: LakkaBios 2024
# Por: Raspberry Pi Buenos Aires ("https://sites.google.com/view/raspberrypibuenosaires/)
# License: http://creativecommons.org/licenses/by-sa/4.0/
###########################################################################
RUTA=https://github.com/PIBSAS/LakkaBios/raw/main/System/
cd
mkdir /storage/system/dc/
mkdir /storage/system/pcsx2/
mkdir /storage/system/pcsx2/bios/
rm "/storage/system/3do_arcade_saot.bin"
rm "/storage/system/goldstar.bin"
rm "/storage/system/panafz10.bin"
rm "/storage/system/panafz10e-anvil.bin"
rm "/storage/system/panafz10e-anvil-norsa.bin"
rm "/storage/system/panafz10ja-anvil-kanji.bin"
rm "/storage/system/panafz10-norsa.bin"
rm "/storage/system/panafz1.bin"
rm "/storage/system/panafz1j.bin"
rm "/storage/system/panafz1j-kanji.bin"
rm "/storage/system/panafz1j-norsa.bin"
rm "/storage/system/panafz1-kanji.bin"
rm "/storage/system/sanyotry.bin"
rm "/storage/system/cpc464.rom"
rm "/storage/system/cpc6128.rom"
rm "/storage/system/cpc664.rom"
rm "/storage/system/cpc_amsdos.rom"
rm "/storage/system/bubsys.zip"
rm "/storage/system/cchip.zip"
rm "/storage/system/decocass.zip"
rm "/storage/system/isgsm.zip"
rm "/storage/system/midssio.zip"
rm "/storage/system/neogeo.zip"
rm "/storage/system/nmk004.zip"
rm "/storage/system/pgm.zip"
rm "/storage/system/skns.zip"
rm "/storage/system/ym2608.zip"
rm "/storage/system/ATARIBAS.ROM"
rm "/storage/system/ATARIOSA.ROM"
rm "/storage/system/ATARIOSB.ROM"
rm "/storage/system/ATARIXL.ROM"
rm "/storage/system/5200.rom"
rm "/storage/system/7800%20BIOS%20(E).rom"
rm "/storage/system/7800%20BIOS%20(U).rom"
rm "/storage/system/lynxboot.img"
rm "/storage/system/tos.img"
rm "/storage/system/colecovision.rom"
rm "/storage/system/kick34005.A500"
rm "/storage/system/kick40063.A600"
rm "/storage/system/kick40068.A1200"
rm "/storage/system/basic20.rom"
rm "/storage/system/basic21.rom"
rm "/storage/system/brd.rom"
rm "/storage/system/epd19hft.rom"
rm "/storage/system/epfileio.rom"
rm "/storage/system/exdos13.rom"
rm "/storage/system/exos20.rom"
rm "/storage/system/exos21.rom"
rm "/storage/system/exos24uk.rom"
rm "/storage/system/hun.rom"
rm "/storage/system/zt18hfnt.rom"
rm "/storage/system/zt19uk.rom"
rm "/storage/system/sl31253.bin"
rm "/storage/system/sl31254.bin"
rm "/storage/system/sl90025.bin"
rm "/storage/system/prboom.wad"
rm "/storage/system/freej2me.jar"
rm "/storage/system/freej2me-lr.jar"
rm "/storage/system/freej2me-sdl.jar"
rm "/storage/system/MacII.ROM"
rm "/storage/system/o2rom.bin"
rm "/storage/system/exec.bin"
rm "/storage/system/grom.bin"
rm "/storage/system/CARTS.SHA"
rm "/storage/system/CYRILLIC.FNT"
rm "/storage/system/DISK.ROM"
rm "/storage/system/FMPAC16.ROM"
rm "/storage/system/FMPAC.ROM"
rm "/storage/system/ITALIC.FNT"
rm "/storage/system/KANJI.ROM"
rm "/storage/system/MSX2EXT.ROM"
rm "/storage/system/MSX2PEXT.ROM"
rm "/storage/system/MSX2P.ROM"
rm "/storage/system/MSX2.ROM"
rm "/storage/system/MSXDOS2.ROM"
rm "/storage/system/MSX.ROM"
rm "/storage/system/PAINTER.ROM"
rm "/storage/system/RS232.ROM"
rm "/storage/system/2608_bd.wav"
rm "/storage/system/2608_hh.wav"
rm "/storage/system/2608_rim.wav"
rm "/storage/system/2608_sd.wav"
rm "/storage/system/2608_tom.wav"
rm "/storage/system/2608_top.wav"
rm "/storage/system/bios.rom"
rm "/storage/system/font.bmp"
rm "/storage/system/font.rom"
rm "/storage/system/itf.rom"
rm "/storage/system/sound.rom"
rm "/storage/system/gecard.pce"
rm "/storage/system/gexpress.pce"
rm "/storage/system/syscard1.pce"
rm "/storage/system/syscard2.pce"
rm "/storage/system/syscard2u.pce"
rm "/storage/system/syscard3.pce"
rm "/storage/system/syscard3u.pce"
rm "/storage/system/fx-scsi.rom"
rm "/storage/system/pcfxbios.bin"
rm "/storage/system/pcfxga.rom"
rm "/storage/system/pcfx.rom"
rm "/storage/system/pcfxv101.bin"
rm "/storage/system/disksys.rom"
rm "/storage/system/dmg_boot.bin"
rm "/storage/system/gb_bios.bin"
rm "/storage/system/gba_bios.bin"
rm "/storage/system/cgb_boot.bin"
rm "/storage/system/gbc_bios.bin"
rm "/storage/system/gc-dvd-20010608.bin"
rm "/storage/system/gc-dvd-20010831.bin"
rm "/storage/system/gc-dvd-20020402.bin"
rm "/storage/system/gc-dvd-20020823.bin"
rm "/storage/system/gc-ntsc-10.bin"
rm "/storage/system/gc-ntsc-11.bin"
rm "/storage/system/gc-ntsc-12.bin"
rm "/storage/system/gc-pal-10.bin"
rm "/storage/system/gc-pal-11.bin"
rm "/storage/system/gc-pal-12.bin"
rm "/storage/system/64DD_IPL.bin"
rm "/storage/system/bios7.bin"
rm "/storage/system/bios9.bin"
rm "/storage/system/firmware.bin"
rm "/storage/system/NstDatabase.xml"
rm "/storage/system/bios.min"
rm "/storage/system/BS-X.bin"
rm "/storage/system/BS-X%20(En).bin"
rm "/storage/system/BS-X%20(En)%20(DRM-Free).bin"
rm "/storage/system/STBIOS.bin"
rm "/storage/system/sgb1.boot.rom"
rm "/storage/system/sgb1.program.rom"
rm "/storage/system/SGB1.sfc"
rm "/storage/system/sgb2_bios.bin"
rm "/storage/system/sgb2.boot.rom"
rm "/storage/system/sgb2.program.rom"
rm "/storage/system/SGB2.sfc"
rm "/storage/system/sgb_bios.bin"
rm "/storage/system/cx4.data.rom"
rm "/storage/system/dsp1b.data.rom"
rm "/storage/system/dsp1b.program.rom"
rm "/storage/system/dsp1.data.rom"
rm "/storage/system/dsp1.program.rom"
rm "/storage/system/dsp2.data.rom"
rm "/storage/system/dsp2.program.rom"
rm "/storage/system/dsp3.data.rom"
rm "/storage/system/dsp3.program.rom"
rm "/storage/system/dsp4.data.rom"
rm "/storage/system/dsp4.program.rom"
rm "/storage/system/st010.data.rom"
rm "/storage/system/st010.program.rom"
rm "/storage/system/st011.data.rom"
rm "/storage/system/st011.program.rom"
rm "/storage/system/st018.data.rom"
rm "/storage/system/st018.program.rom"
rm "/storage/system/c52.bin"
rm "/storage/system/g7400.bin"
rm "/storage/system/jopac.bin"
rm "/storage/system/scummvm.zip"
rm "/storage/system/dc/boot.bin"
rm "/storage/system/dc/dc_boot.bin"
rm "/storage/system/dc/flash.bin"
rm "/storage/system/dc/airlbios.zip"
rm "/storage/system/dc/awbios.zip"
rm "/storage/system/dc/f355bios.zip"
rm "/storage/system/dc/f355dlx.zip"
rm "/storage/system/dc/hod2bios.zip"
rm "/storage/system/dc/naomi2.zip"
rm "/storage/system/dc/naomi.zip"
rm "/storage/system/bios.gg"
rm "/storage/system/bios_E.sms"
rm "/storage/system/bios_J.sms"
rm "/storage/system/bios.sms"
rm "/storage/system/bios_U.sms"
rm "/storage/system/bios_CD_E.bin"
rm "/storage/system/bios_CD_J.bin"
rm "/storage/system/bios_CD_U.bin"
rm "/storage/system/areplay.bin"
rm "/storage/system/bios_MD.bin"
rm "/storage/system/ggenie.bin"
rm "/storage/system/rom.db"
rm "/storage/system/sk2chip.bin"
rm "/storage/system/sk.bin"
rm "/storage/system/hisaturn.bin"
rm "/storage/system/mpr-17933.bin"
rm "/storage/system/mpr-18100.bin"
rm "/storage/system/mpr-18811-mx.ic1"
rm "/storage/system/mpr-19367-mx.ic1"
rm "/storage/system/saturn_bios.bin"
rm "/storage/system/sega1003.bin"
rm "/storage/system/sega_100a.bin"
rm "/storage/system/sega_100.bin"
rm "/storage/system/sega_101.bin"
rm "/storage/system/vsaturn.bin"
rm "/storage/system/iplrom.x1"
rm "/storage/system/iplrom.x1t"
rm "/storage/system/cgrom.dat"
rm "/storage/system/iplrom30.dat"
rm "/storage/system/iplromco.dat"
rm "/storage/system/iplrom.dat"
rm "/storage/system/iplromxv.dat"
rm "/storage/system/128-0.rom"
rm "/storage/system/128-1.rom"
rm "/storage/system/128p-0.rom"
rm "/storage/system/128p-1.rom"
rm "/storage/system/128-spanish-0.rom"
rm "/storage/system/128-spanish-1.rom"
rm "/storage/system/256s-0.rom"
rm "/storage/system/256s-1.rom"
rm "/storage/system/256s-2.rom"
rm "/storage/system/256s-3.rom"
rm "/storage/system/48.rom"
rm "/storage/system/disciple.rom"
rm "/storage/system/disk_plus3.szx"
rm "/storage/system/gluck.rom"
rm "/storage/system/if1-1.rom"
rm "/storage/system/if1-2.rom"
rm "/storage/system/plus2-0.rom"
rm "/storage/system/plus2-1.rom"
rm "/storage/system/plus3-0.rom"
rm "/storage/system/plus3-1.rom"
rm "/storage/system/plus3-2.rom"
rm "/storage/system/plus3-3.rom"
rm "/storage/system/plus3e-0.rom"
rm "/storage/system/plus3e-1.rom"
rm "/storage/system/plus3e-2.rom"
rm "/storage/system/plus3e-3.rom"
rm "/storage/system/plusd.rom"
rm "/storage/system/se-0.rom"
rm "/storage/system/se-1.rom"
rm "/storage/system/speccyboot-1.4.rom"
rm "/storage/system/tape_128.szx"
rm "/storage/system/tape_16.szx"
rm "/storage/system/tape_2048.szx"
rm "/storage/system/tape_2068.szx"
rm "/storage/system/tape_48.szx"
rm "/storage/system/tape_pentagon.szx"
rm "/storage/system/tape_plus2a.szx"
rm "/storage/system/tape_plus2.szx"
rm "/storage/system/tape_plus3e.szx"
rm "/storage/system/tape_plus3.szx"
rm "/storage/system/tape_scorpion.szx"
rm "/storage/system/tape_se.szx"
rm "/storage/system/tape_ts2068.szx"
rm "/storage/system/tc2048.rom"
rm "/storage/system/tc2068-0.rom"
rm "/storage/system/tc2068-1.rom"
rm "/storage/system/trdos.rom"
rm "/storage/system/zx128.rom"
rm "/storage/system/zx48.rom"
rm "/storage/system/000-lo.lo"
rm "/storage/system/front-sp1.bin"
rm "/storage/system/neocd.bin"
rm "/storage/system/neocd_f.rom"
rm "/storage/system/neocd_sf.rom"
rm "/storage/system/neocd_st.rom"
rm "/storage/system/neocd_sz.rom"
rm "/storage/system/neocd_t.rom"
rm "/storage/system/neocd_z.rom"
rm "/storage/system/top-sp1.bin"
rm "/storage/system/uni-bioscd.rom"
rm "/storage/system/scph1000.bin"
rm "/storage/system/scph1001.bin"
rm "/storage/system/scph1002.bin"
rm "/storage/system/scph100.bin"
rm "/storage/system/scph101.bin"
rm "/storage/system/scph102A.bin"
rm "/storage/system/scph102B.bin"
rm "/storage/system/scph102C.bin"
rm "/storage/system/scph3000.bin"
rm "/storage/system/scph3500.bin"
rm "/storage/system/scph5000.bin"
rm "/storage/system/scph5500.bin"
rm "/storage/system/scph5501.bin"
rm "/storage/system/scph5502.bin"
rm "/storage/system/scph5552.bin"
rm "/storage/system/scph7001.bin"
rm "/storage/system/scph7002.bin"
rm "/storage/system/scph7003.bin"
rm "/storage/system/scph7502.bin"
rm "/storage/system/scph9002(7502).bin"
rm "/storage/system/pcsx2/bios/ps2-0100j-20000117.bin"
rm "/storage/system/pcsx2/bios/ps2-0100jd-20000117.bin"
rm "/storage/system/pcsx2/bios/ps2-0101j-20000217.bin"
rm "/storage/system/pcsx2/bios/ps2-0101jd-20000217.bin"
rm "/storage/system/pcsx2/bios/ps2-0101xd-20000224.bin"
rm "/storage/system/pcsx2/bios/ps2-0110a-20000727.bin"
rm "/storage/system/pcsx2/bios/ps2-0110ad-20000727.bin"
rm "/storage/system/pcsx2/bios/ps2-0120a-20000902.bin"
rm "/storage/system/pcsx2/bios/ps2-0120e-20000902.bin"
rm "/storage/system/pcsx2/bios/ps2-0120ed-20000902-20030110.bin"
rm "/storage/system/pcsx2/bios/ps2-0120ed-20000902.bin"
rm "/storage/system/pcsx2/bios/ps2-0120j-20001027-185015.bin"
rm "/storage/system/pcsx2/bios/ps2-0120j-20001027-191435.bin"
rm "/storage/system/pcsx2/bios/ps2-0150a-20001228.bin"
rm "/storage/system/pcsx2/bios/ps2-0150ad-20001228-20030520.bin"
rm "/storage/system/pcsx2/bios/ps2-0150e-20001228.bin"
rm "/storage/system/pcsx2/bios/ps2-0150ed-20001228-20030520.bin"
rm "/storage/system/pcsx2/bios/ps2-0150j-20010118.bin"
rm "/storage/system/pcsx2/bios/ps2-0150jd-20010118.bin"
rm "/storage/system/pcsx2/bios/ps2-0160a-20010427.bin"
rm "/storage/system/pcsx2/bios/ps2-0160a-20010704.bin"
rm "/storage/system/pcsx2/bios/ps2-0160a-20011004.bin"
rm "/storage/system/pcsx2/bios/ps2-0160a-20020207.bin"
rm "/storage/system/pcsx2/bios/ps2-0160e-20010704.bin"
rm "/storage/system/pcsx2/bios/ps2-0160e-20011004.bin"
rm "/storage/system/pcsx2/bios/ps2-0160e-20020319.bin"
rm "/storage/system/pcsx2/bios/ps2-0160e-20020426.bin"
rm "/storage/system/pcsx2/bios/ps2-0160h-20010730.bin"
rm "/storage/system/pcsx2/bios/ps2-0160h-20020426.bin"
rm "/storage/system/pcsx2/bios/ps2-0160j-20010427.bin"
rm "/storage/system/pcsx2/bios/ps2-0160j-20020426.bin"
rm "/storage/system/pcsx2/bios/ps2-0170a-20030325.bin"
rm "/storage/system/pcsx2/bios/ps2-0170ad-20030325.bin"
rm "/storage/system/pcsx2/bios/ps2-0170e-20030227.bin"
rm "/storage/system/pcsx2/bios/ps2-0170ed-20030227.bin"
rm "/storage/system/pcsx2/bios/ps2-0170j-20030206.bin"
rm "/storage/system/pcsx2/bios/ps2-0180cd-20030224.bin"
rm "/storage/system/pcsx2/bios/ps2-0180j-20031028.bin"
rm "/storage/system/pcsx2/bios/ps2-0190a-20030623.bin"
rm "/storage/system/pcsx2/bios/ps2-0190a-20040329.bin"
rm "/storage/system/pcsx2/bios/ps2-0190c-20030623.bin"
rm "/storage/system/pcsx2/bios/ps2-0190e-20030623.bin"
rm "/storage/system/pcsx2/bios/ps2-0190e-20030822.bin"
rm "/storage/system/pcsx2/bios/ps2-0190h-20030623.bin"
rm "/storage/system/pcsx2/bios/ps2-0190j-20030623.bin"
rm "/storage/system/pcsx2/bios/ps2-0190j-20030822.bin"
rm "/storage/system/pcsx2/bios/ps2-0190r-20030623.bin"
rm "/storage/system/pcsx2/bios/ps2-0200a-20040614.bin"
rm "/storage/system/pcsx2/bios/ps2-0200e-20040614.bin"
rm "/storage/system/pcsx2/bios/ps2-0200ed-20040614.bin"
rm "/storage/system/pcsx2/bios/ps2-0200h-20040614.bin"
rm "/storage/system/pcsx2/bios/ps2-0200j-20040614.bin"
rm "/storage/system/pcsx2/bios/ps2-0210j-20040917.bin"
rm "/storage/system/pcsx2/bios/ps2-0220a-20050620.bin"
rm "/storage/system/pcsx2/bios/ps2-0220a-20060210.bin"
rm "/storage/system/pcsx2/bios/ps2-0220a-20060905.bin"
rm "/storage/system/pcsx2/bios/ps2-0220ad-20050620.bin"
rm "/storage/system/pcsx2/bios/ps2-0220ad-20060905.bin"
rm "/storage/system/pcsx2/bios/ps2-0220e-20050620.bin"
rm "/storage/system/pcsx2/bios/ps2-0220e-20060210.bin"
rm "/storage/system/pcsx2/bios/ps2-0220e-20060905.bin"
rm "/storage/system/pcsx2/bios/ps2-0220h-20050620.bin"
rm "/storage/system/pcsx2/bios/ps2-0220h-20060210.bin"
rm "/storage/system/pcsx2/bios/ps2-0220h-20060905.bin"
rm "/storage/system/pcsx2/bios/ps2-0220j-20050620.bin"
rm "/storage/system/pcsx2/bios/ps2-0220j-20060210.bin"
rm "/storage/system/pcsx2/bios/ps2-0220j-20060905.bin"
rm "/storage/system/pcsx2/bios/ps2-0230a-20080220.bin"
rm "/storage/system/pcsx2/bios/ps2-0230e-20080220.bin"
rm "/storage/system/pcsx2/bios/ps2-0230h-20080220.bin"
rm "/storage/system/pcsx2/bios/ps2-0230j-20080220.bin"
rm "/storage/system/pcsx2/bios/ps2-0250e-20100415.bin"
rm "/storage/system/pcsx2/bios/ps2-0250j-20100415.bin"
rm "/storage/system/ppge_atlas.zim"
rm "/storage/system/tvc22_ext.rom"
rm "/storage/system/tvc22_sys.rom"
rm "/storage/system/tvc_dos12d.rom"
rm "/storage/system/tvcfileio.rom"
rm "/storage/system/ecwolf.pk3"

echo "The 3DO Company"
wget -c "${RUTA}3DO%20Company%2C%20The%20-%203DO/3do_arcade_saot.bin" -P /storage/system/
wget -c "${RUTA}3DO%20Company%2C%20The%20-%203DO/goldstar.bin" -P /storage/system/
wget -c "${RUTA}3DO%20Company%2C%20The%20-%203DO/panafz10.bin" -P /storage/system/
wget -c "${RUTA}3DO%20Company%2C%20The%20-%203DO/panafz10e-anvil.bin" -P /storage/system/
wget -c "${RUTA}3DO%20Company%2C%20The%20-%203DO/panafz10e-anvil-norsa.bin" -P /storage/system/
wget -c "${RUTA}3DO%20Company%2C%20The%20-%203DO/panafz10ja-anvil-kanji.bin" -P /storage/system/
wget -c "${RUTA}3DO%20Company%2C%20The%20-%203DO/panafz10-norsa.bin" -P /storage/system/
wget -c "${RUTA}3DO%20Company%2C%20The%20-%203DO/panafz1.bin" -P /storage/system/
wget -c "${RUTA}3DO%20Company%2C%20The%20-%203DO/panafz1j.bin" -P /storage/system/
wget -c "${RUTA}3DO%20Company%2C%20The%20-%203DO/panafz1j-kanji.bin" -P /storage/system/
wget -c "${RUTA}3DO%20Company%2C%20The%20-%203DO/panafz1j-norsa.bin" -P /storage/system/
wget -c "${RUTA}3DO%20Company%2C%20The%20-%203DO/panafz1-kanji.bin" -P /storage/system/
wget -c "${RUTA}3DO%20Company%2C%20The%20-%203DO/sanyotry.bin" -P /storage/system/

echo "Amstrad-CPC"
wget -c "${RUTA}Amstrad%20-%20CPC/cpc464.rom" -P /storage/system/
wget -c "${RUTA}Amstrad%20-%20CPC/cpc6128.rom" -P /storage/system/
wget -c "${RUTA}Amstrad%20-%20CPC/cpc664.rom" -P /storage/system/
wget -c "${RUTA}Amstrad%20-%20CPC/cpc_amsdos.rom" -P /storage/system/

echo "Arcade"
wget -c "${RUTA}Arcade/bubsys.zip" -P /storage/system/
wget -c "${RUTA}Arcade/cchip.zip" -P /storage/system/
wget -c "${RUTA}Arcade/decocass.zip" -P /storage/system/
wget -c "${RUTA}Arcade/isgsm.zip" -P /storage/system/
wget -c "${RUTA}Arcade/midssio.zip" -P /storage/system/
wget -c "${RUTA}Arcade/neogeo.zip" -P /storage/system/
wget -c "${RUTA}Arcade/nmk004.zip" -P /storage/system/
wget -c "${RUTA}Arcade/pgm.zip" -P /storage/system/
wget -c "${RUTA}Arcade/skns.zip" -P /storage/system/
wget -c "${RUTA}Arcade/ym2608.zip" -P /storage/system/

echo "Atari-400-800"
wget -c "${RUTA}Atari%20-%20400-800/ATARIBAS.ROM" -P /storage/system/
wget -c "${RUTA}Atari%20-%20400-800/ATARIOSA.ROM" -P /storage/system/
wget -c "${RUTA}Atari%20-%20400-800/ATARIOSB.ROM" -P /storage/system/
wget -c "${RUTA}Atari%20-%20400-800/ATARIXL.ROM" -P /storage/system/

echo "Atari-5200"
wget -c "${RUTA}Atari%20-%205200/5200.rom" -P /storage/system/

echo "Atari-7800"
wget -c "${RUTA}Atari%20-%207800/7800%20BIOS%20(E).rom" -P /storage/system/
wget -c "${RUTA}Atari%20-%207800/7800%20BIOS%20(U).rom" -P /storage/system/

echo "Atari-Lynx"
wget -c "${RUTA}Atari%20-%20Lynx/lynxboot.img" -P /storage/system/

echo "Atari-ST"
wget -c "${RUTA}Atari%20-%20ST/tos.img" -P /storage/system/

echo "Coleco-ColecoVision"
wget -c "${RUTA}Coleco%20-%20ColecoVision/colecovision.rom" -P /storage/system/

echo "Commodore-Amiga"
wget -c "${RUTA}Commodore%20-%20Amiga/kick34005.A500" -P /storage/system/
wget -c "${RUTA}Commodore%20-%20Amiga/kick40063.A600" -P /storage/system/
wget -c "${RUTA}Commodore%20-%20Amiga/kick40068.A1200" -P /storage/system/

echo "Enterprise-64-128"
wget -c "${RUTA}Enterprise%20-%2064-128/basic20.rom" -P /storage/system/
wget -c "${RUTA}Enterprise%20-%2064-128/basic21.rom" -P /storage/system/
wget -c "${RUTA}Enterprise%20-%2064-128/brd.rom" -P /storage/system/
wget -c "${RUTA}Enterprise%20-%2064-128/epd19hft.rom" -P /storage/system/
wget -c "${RUTA}Enterprise%20-%2064-128/epfileio.rom" -P /storage/system/
wget -c "${RUTA}Enterprise%20-%2064-128/exdos13.rom" -P /storage/system/
wget -c "${RUTA}Enterprise%20-%2064-128/exos20.rom" -P /storage/system/
wget -c "${RUTA}Enterprise%20-%2064-128/exos21.rom" -P /storage/system/
wget -c "${RUTA}Enterprise%20-%2064-128/exos24uk.rom" -P /storage/system/
wget -c "${RUTA}Enterprise%20-%2064-128/hun.rom" -P /storage/system/
wget -c "${RUTA}Enterprise%20-%2064-128/zt18hfnt.rom" -P /storage/system/
wget -c "${RUTA}Enterprise%20-%2064-128/zt19uk.rom" -P /storage/system/

echo "Fairchild Channel F"
wget -c "${RUTA}Fairchild%20Channel%20F/sl31253.bin" -P /storage/system/
wget -c "${RUTA}Fairchild%20Channel%20F/sl31254.bin" -P /storage/system/
wget -c "${RUTA}Fairchild%20Channel%20F/sl90025.bin" -P /storage/system/

echo "Id Software-Doom"
wget -c "${RUTA}Id%20Software%20-%20Doom/prboom.wad" -P /storage/system/

echo "J2ME"
wget -c "${RUTA}J2ME/freej2me.jar" -P /storage/system/
wget -c "${RUTA}J2ME/freej2me-lr.jar" -P /storage/system/
wget -c "${RUTA}J2ME/freej2me-sdl.jar" -P /storage/system/

echo "MacII"
wget -c "${RUTA}MacII/MacII.ROM" -P /storage/system/

echo "Magnavox-Odyssey2"
wget -c "${RUTA}Magnavox%20-%20Odyssey2/o2rom.bin" -P /storage/system/

echo "Mattel-Intellivision"
wget -c "${RUTA}Mattel%20-%20Intellivision/exec.bin" -P /storage/system/
wget -c "${RUTA}Mattel%20-%20Intellivision/grom.bin" -P /storage/system/

echo "Microsoft-MSX"
wget -c "${RUTA}Microsoft%20-%20MSX/CARTS.SHA" -P /storage/system/
wget -c "${RUTA}Microsoft%20-%20MSX/CYRILLIC.FNT" -P /storage/system/
wget -c "${RUTA}Microsoft%20-%20MSX/DISK.ROM" -P /storage/system/
wget -c "${RUTA}Microsoft%20-%20MSX/FMPAC16.ROM" -P /storage/system/
wget -c "${RUTA}Microsoft%20-%20MSX/FMPAC.ROM" -P /storage/system/
wget -c "${RUTA}Microsoft%20-%20MSX/ITALIC.FNT" -P /storage/system/
wget -c "${RUTA}Microsoft%20-%20MSX/KANJI.ROM" -P /storage/system/
wget -c "${RUTA}Microsoft%20-%20MSX/MSX2EXT.ROM" -P /storage/system/
wget -c "${RUTA}Microsoft%20-%20MSX/MSX2PEXT.ROM" -P /storage/system/
wget -c "${RUTA}Microsoft%20-%20MSX/MSX2P.ROM" -P /storage/system/
wget -c "${RUTA}Microsoft%20-%20MSX/MSX2.ROM" -P /storage/system/
wget -c "${RUTA}Microsoft%20-%20MSX/MSXDOS2.ROM" -P /storage/system/
wget -c "${RUTA}Microsoft%20-%20MSX/MSX.ROM" -P /storage/system/
wget -c "${RUTA}Microsoft%20-%20MSX/PAINTER.ROM" -P /storage/system/
wget -c "${RUTA}Microsoft%20-%20MSX/RS232.ROM" -P /storage/system/

echo "NEC-PC-98"
wget -c "${RUTA}NEC%20-%20PC-98/2608_bd.wav" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC-98/2608_hh.wav" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC-98/2608_rim.wav" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC-98/2608_sd.wav" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC-98/2608_tom.wav" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC-98/2608_top.wav" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC-98/bios.rom" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC-98/font.bmp" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC-98/font.rom" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC-98/itf.rom" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC-98/sound.rom" -P /storage/system/

echo "NEC-PC Engine-TurboGrafx 16-SuperGrafx"
wget -c "${RUTA}NEC%20-%20PC%20Engine%20-%20TurboGrafx%2016%20-%20SuperGrafx/gecard.pce" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC%20Engine%20-%20TurboGrafx%2016%20-%20SuperGrafx/gexpress.pce" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC%20Engine%20-%20TurboGrafx%2016%20-%20SuperGrafx/syscard1.pce" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC%20Engine%20-%20TurboGrafx%2016%20-%20SuperGrafx/syscard2.pce" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC%20Engine%20-%20TurboGrafx%2016%20-%20SuperGrafx/syscard2u.pce" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC%20Engine%20-%20TurboGrafx%2016%20-%20SuperGrafx/syscard3.pce" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC%20Engine%20-%20TurboGrafx%2016%20-%20SuperGrafx/syscard3u.pce" -P /storage/system/

echo "NEC-PC-FX"
wget -c "${RUTA}NEC%20-%20PC-FX/fx-scsi.rom" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC-FX/pcfxbios.bin" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC-FX/pcfxga.rom" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC-FX/pcfx.rom" -P /storage/system/
wget -c "${RUTA}NEC%20-%20PC-FX/pcfxv101.bin" -P /storage/system/

echo "Nintendo-Famicom Disk System"
wget -c "${RUTA}Nintendo%20-%20Famicom%20Disk%20System/disksys.rom" -P /storage/system/

echo "Nintendo-Gameboy"
wget -c "${RUTA}Nintendo%20-%20Gameboy/dmg_boot.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Gameboy/gb_bios.bin" -P /storage/system/

echo "Nintendo-Game Boy Advance"
wget -c "${RUTA}Nintendo%20-%20Game%20Boy%20Advance/gba_bios.bin" -P /storage/system/

echo "Nintendo-Gameboy Color"
wget -c "${RUTA}Nintendo%20-%20Gameboy%20Color/cgb_boot.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Gameboy%20Color/gbc_bios.bin" -P /storage/system/

echo "Nintendo-GameCube"
wget -c "${RUTA}Nintendo%20-%20GameCube/gc-dvd-20010608.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20GameCube/gc-dvd-20010831.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20GameCube/gc-dvd-20020402.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20GameCube/gc-dvd-20020823.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20GameCube/gc-ntsc-10.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20GameCube/gc-ntsc-11.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20GameCube/gc-ntsc-12.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20GameCube/gc-pal-10.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20GameCube/gc-pal-11.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20GameCube/gc-pal-12.bin" -P /storage/system/

echo "Nintendo-Nintendo 64DD"
wget -c "${RUTA}Nintendo%20-%20Nintendo%2064DD/64DD_IPL.bin" -P /storage/system/

echo "Nintendo-Nintendo DS"
wget -c "${RUTA}Nintendo%20-%20Nintendo%20DS/bios7.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Nintendo%20DS/bios9.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Nintendo%20DS/firmware.bin" -P /storage/system/

echo "Nintendo-Nintendo Entertainment System"
wget -c "${RUTA}Nintendo%20-%20Nintendo%20Entertainment%20System/NstDatabase.xml" -P /storage/system/

echo "Nintendo-Pokemon Mini"
wget -c "${RUTA}Nintendo%20-%20Pokemon%20Mini/bios.min" -P /storage/system/

echo "Nintendo-Satellaview"
wget -c "${RUTA}Nintendo%20-%20Satellaview/BS-X.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Satellaview/BS-X%20(En).bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Satellaview/BS-X%20(En)%20(DRM-Free).bin" -P /storage/system/

echo "Nintendo-SuFami Turbo"
wget -c "${RUTA}Nintendo%20-%20SuFami%20Turbo/STBIOS.bin" -P /storage/system/

echo "Nintendo-Super Game Boy"
wget -c "${RUTA}Nintendo%20-%20Super%20Game%20Boy/sgb1.boot.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Game%20Boy/sgb1.program.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Game%20Boy/SGB1.sfc" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Game%20Boy/sgb2_bios.bin" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Game%20Boy/sgb2.boot.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Game%20Boy/sgb2.program.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Game%20Boy/SGB2.sfc" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Game%20Boy/sgb_bios.bin" -P /storage/system/

echo "Nintendo-Super Nintendo Entertainment System"
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/cx4.data.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/dsp1b.data.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/dsp1b.program.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/dsp1.data.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/dsp1.program.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/dsp2.data.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/dsp2.program.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/dsp3.data.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/dsp3.program.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/dsp4.data.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/dsp4.program.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/st010.data.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/st010.program.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/st011.data.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/st011.program.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/st018.data.rom" -P /storage/system/
wget -c "${RUTA}Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/st018.program.rom" -P /storage/system/

echo "Phillips-Videopac+"
wget -c "${RUTA}Phillips%20-%20Videopac+/c52.bin" -P /storage/system/
wget -c "${RUTA}Phillips%20-%20Videopac+/g7400.bin" -P /storage/system/
wget -c "${RUTA}Phillips%20-%20Videopac+/jopac.bin" -P /storage/system/

echo "ScummVM"
wget -c "${RUTA}ScummVM/scummvm.zip" -P /storage/system/

echo "Sega-Dreamcast/dc"
wget -c "${RUTA}Sega%20-%20Dreamcast/dc/boot.bin" -P /storage/system/dc/
wget -c "${RUTA}Sega%20-%20Dreamcast/dc/dc_boot.bin" -P /storage/system/dc/
wget -c "${RUTA}Sega%20-%20Dreamcast/dc/flash.bin" -P /storage/system/dc/

echo "Sega-Dreamcast-based Arcade/dc"
wget -c "${RUTA}Sega%20-%20Dreamcast-based%20Arcade/dc/airlbios.zip" -P /storage/system/dc/
wget -c "${RUTA}Sega%20-%20Dreamcast-based%20Arcade/dc/awbios.zip" -P /storage/system/dc/
wget -c "${RUTA}Sega%20-%20Dreamcast-based%20Arcade/dc/f355bios.zip" -P /storage/system/dc/
wget -c "${RUTA}Sega%20-%20Dreamcast-based%20Arcade/dc/f355dlx.zip" -P /storage/system/dc/
wget -c "${RUTA}Sega%20-%20Dreamcast-based%20Arcade/dc/hod2bios.zip" -P /storage/system/dc/
wget -c "${RUTA}Sega%20-%20Dreamcast-based%20Arcade/dc/naomi2.zip" -P /storage/system/dc/
wget -c "${RUTA}Sega%20-%20Dreamcast-based%20Arcade/dc/naomi.zip" -P /storage/system/dc/

echo "Sega-Game Gear"
wget -c "${RUTA}Sega%20-%20Game%20Gear/bios.gg" -P /storage/system/

echo "Sega-Master System-Mark III"
wget -c "${RUTA}Sega%20-%20Master%20System%20-%20Mark%20III/bios_E.sms" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Master%20System%20-%20Mark%20III/bios_J.sms" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Master%20System%20-%20Mark%20III/bios.sms" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Master%20System%20-%20Mark%20III/bios_U.sms" -P /storage/system/

echo "Sega-Mega CD-Sega CD"
wget -c "${RUTA}Sega%20-%20Mega%20CD%20-%20Sega%20CD/bios_CD_E.bin" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Mega%20CD%20-%20Sega%20CD/bios_CD_J.bin" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Mega%20CD%20-%20Sega%20CD/bios_CD_U.bin" -P /storage/system/

echo "Sega-Mega Drive-Genesis"
wget -c "${RUTA}Sega%20-%20Mega%20Drive%20-%20Genesis/areplay.bin" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Mega%20Drive%20-%20Genesis/bios_MD.bin" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Mega%20Drive%20-%20Genesis/ggenie.bin" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Mega%20Drive%20-%20Genesis/rom.db" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Mega%20Drive%20-%20Genesis/sk2chip.bin" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Mega%20Drive%20-%20Genesis/sk.bin" -P /storage/system/

echo "Sega-Saturn"
wget -c "${RUTA}Sega%20-%20Saturn/hisaturn.bin" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Saturn/mpr-17933.bin" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Saturn/mpr-18100.bin" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Saturn/mpr-18811-mx.ic1" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Saturn/mpr-19367-mx.ic1" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Saturn/saturn_bios.bin" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Saturn/sega1003.bin" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Saturn/sega_100a.bin" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Saturn/sega_100.bin" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Saturn/sega_101.bin" -P /storage/system/
wget -c "${RUTA}Sega%20-%20Saturn/vsaturn.bin" -P /storage/system/

echo "Sharp-X1"
wget -c "${RUTA}Sharp%20-%20X1/iplrom.x1" -P /storage/system/
wget -c "${RUTA}Sharp%20-%20X1/iplrom.x1t" -P /storage/system/

echo "Sharp-X68000"
wget -c "${RUTA}Sharp%20-%20X68000/cgrom.dat" -P /storage/system/
wget -c "${RUTA}Sharp%20-%20X68000/iplrom30.dat" -P /storage/system/
wget -c "${RUTA}Sharp%20-%20X68000/iplromco.dat" -P /storage/system/
wget -c "${RUTA}Sharp%20-%20X68000/iplrom.dat" -P /storage/system/
wget -c "${RUTA}Sharp%20-%20X68000/iplromxv.dat" -P /storage/system/

echo "Sinclair-ZX Spectrum"
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/128-0.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/128-1.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/128p-0.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/128p-1.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/128-spanish-0.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/128-spanish-1.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/256s-0.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/256s-1.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/256s-2.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/256s-3.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/48.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/disciple.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/disk_plus3.szx" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/gluck.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/if1-1.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/if1-2.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/plus2-0.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/plus2-1.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/plus3-0.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/plus3-1.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/plus3-2.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/plus3-3.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/plus3e-0.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/plus3e-1.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/plus3e-2.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/plus3e-3.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/plusd.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/se-0.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/se-1.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/speccyboot-1.4.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tape_128.szx" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tape_16.szx" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tape_2048.szx" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tape_2068.szx" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tape_48.szx" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tape_pentagon.szx" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tape_plus2a.szx" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tape_plus2.szx" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tape_plus3e.szx" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tape_plus3.szx" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tape_scorpion.szx" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tape_se.szx" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tape_ts2068.szx" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tc2048.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tc2068-0.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/tc2068-1.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/trdos.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/zx128.rom" -P /storage/system/
wget -c "${RUTA}Sinclair%20-%20ZX%20Spectrum/zx48.rom" -P /storage/system/

echo "SNK-NeoGeo CD"
wget -c "${RUTA}SNK%20-%20NeoGeo%20CD/000-lo.lo" -P /storage/system/
wget -c "${RUTA}SNK%20-%20NeoGeo%20CD/front-sp1.bin" -P /storage/system/
wget -c "${RUTA}SNK%20-%20NeoGeo%20CD/neocd.bin" -P /storage/system/
wget -c "${RUTA}SNK%20-%20NeoGeo%20CD/neocd_f.rom" -P /storage/system/
wget -c "${RUTA}SNK%20-%20NeoGeo%20CD/neocd_sf.rom" -P /storage/system/
wget -c "${RUTA}SNK%20-%20NeoGeo%20CD/neocd_st.rom" -P /storage/system/
wget -c "${RUTA}SNK%20-%20NeoGeo%20CD/neocd_sz.rom" -P /storage/system/
wget -c "${RUTA}SNK%20-%20NeoGeo%20CD/neocd_t.rom" -P /storage/system/
wget -c "${RUTA}SNK%20-%20NeoGeo%20CD/neocd_z.rom" -P /storage/system/
wget -c "${RUTA}SNK%20-%20NeoGeo%20CD/top-sp1.bin" -P /storage/system/
wget -c "${RUTA}SNK%20-%20NeoGeo%20CD/uni-bioscd.rom" -P /storage/system/

echo "Sony-PlayStation"
wget -c "${RUTA}Sony%20-%20PlayStation/scph1000.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph1001.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph1002.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph100.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph101.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph102A.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph102B.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph102C.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph3000.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph3500.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph5000.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph5500.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph5501.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph5502.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph5552.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph7001.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph7002.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph7003.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph7502.bin" -P /storage/system/
wget -c "${RUTA}Sony%20-%20PlayStation/scph9002(7502).bin" -P /storage/system/

echo "Sony-PlayStation 2 /pcsx2/bios"
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0100j-20000117.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0100jd-20000117.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0101j-20000217.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0101jd-20000217.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0101xd-20000224.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0110a-20000727.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0110ad-20000727.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0120a-20000902.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0120e-20000902.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0120ed-20000902-20030110.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0120ed-20000902.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0120j-20001027-185015.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0120j-20001027-191435.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0150a-20001228.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0150ad-20001228-20030520.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0150e-20001228.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0150ed-20001228-20030520.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0150j-20010118.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0150jd-20010118.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0160a-20010427.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0160a-20010704.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0160a-20011004.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0160a-20020207.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0160e-20010704.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0160e-20011004.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0160e-20020319.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0160e-20020426.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0160h-20010730.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0160h-20020426.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0160j-20010427.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0160j-20020426.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0170a-20030325.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0170ad-20030325.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0170e-20030227.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0170ed-20030227.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0170j-20030206.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0180cd-20030224.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0180j-20031028.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0190a-20030623.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0190a-20040329.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0190c-20030623.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0190e-20030623.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0190e-20030822.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0190h-20030623.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0190j-20030623.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0190j-20030822.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0190r-20030623.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0200a-20040614.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0200e-20040614.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0200ed-20040614.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0200h-20040614.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0200j-20040614.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0210j-20040917.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0220a-20050620.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0220a-20060210.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0220a-20060905.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0220ad-20050620.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0220ad-20060905.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0220e-20050620.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0220e-20060210.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0220e-20060905.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0220h-20050620.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0220h-20060210.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0220h-20060905.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0220j-20050620.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0220j-20060210.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0220j-20060905.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0230a-20080220.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0230e-20080220.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0230h-20080220.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0230j-20080220.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0250e-20100415.bin" -P /storage/system/pcsx2/bios/
wget -c "${RUTA}Sony%20-%20PlayStation%202/pcsx2/bios/ps2-0250j-20100415.bin" -P /storage/system/pcsx2/bios/

echo "Sony-PlayStation Portable"
wget -c "${RUTA}Sony%20-%20PlayStation%20Portable/ppge_atlas.zim" -P /storage/system/

echo "Videoton-TV Computer"
wget -c "${RUTA}Videoton%20-%20TV%20Computer/tvc22_ext.rom" -P /storage/system/
wget -c "${RUTA}Videoton%20-%20TV%20Computer/tvc22_sys.rom" -P /storage/system/
wget -c "${RUTA}Videoton%20-%20TV%20Computer/tvc_dos12d.rom" -P /storage/system/
wget -c "${RUTA}Videoton%20-%20TV%20Computer/tvcfileio.rom" -P /storage/system/

echo "Wolfenstein 3D"
wget -c "${RUTA}Wolfenstein%203D/ecwolf.pk3" -P /storage/system/
echo "That's all!"
